read -r -p "Enter the domain or URL for your site (e.g., example.com): " url && sudo apt update && sudo apt install -y nginx certbot python3-certbot-nginx &&  sudo certbot --nginx -d $url --register-unsafely-without-email --agree-tos --non-interactive && sudo service nginx start && echo "server { listen 443 ssl; listen [::]:443 ssl; server_name $url; ssl_certificate /etc/letsencrypt/live/$url/fullchain.pem; ssl_certificate_key /etc/letsencrypt/live/$url/privkey.pem; location / { proxy_pass http://127.0.0.1:8080; proxy_set_header Host \$host; proxy_set_header X-Real-IP \$remote_addr; proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for; proxy_set_header X-Forwarded-Proto \$scheme; } error_log /var/log/nginx/error.log;access_log /var/log/nginx/access.log; }" | sudo tee /etc/nginx/sites-available/$url > /dev/null && sudo ln -s /etc/nginx/sites-available/$url /etc/nginx/sites-enabled/ && sudo nginx -t && sudo systemctl reload nginx && sleep 10 &&  sudo apt install docker.io -y && sudo systemctl start docker && sudo systemctl enable docker &&  sudo curl -L "https://github.com/docker/compose/releases/download/v2.20.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose && sudo chmod +x /usr/local/bin/docker-compose &&  sudo apt install git -y  && cd / && git clone https://github.com/xibosignage/xibo-docker.git && cd xibo-docker && sed -i 's/80:80/8080:80/g' docker-compose.yml && echo "MYSQL_PASSWORD=MySecut735uh
CMS_SMTP_SERVER=smtp.gmail.com:587
CMS_SMTP_USERNAME=youraccount@gmail.com
CMS_SMTP_PASSWORD=yourpassword
CMS_SMTP_USE_TLS=YES
CMS_SMTP_USE_STARTTLS=YES
CMS_SMTP_REWRITE_DOMAIN=gmail.com
CMS_SMTP_HOSTNAME=gmail.com
CMS_SMTP_FROM_LINE_OVERRIDE=YES
CMS_SERVER_NAME= $url " | sudo tee config.env > /dev/null  && sudo docker-compose up -d
